image: python:3.9

stages:
- test
- package
- deploy
- docs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
  - .cache/pip
  - venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate


flake8:
  stage: test
  before_script:
  - pip install flake8
  script:
  - flake8 --exclude venv zip_deployer #tests

pytest:
  stage: test
  before_script:
  - export PYTHONPATH="$PYTHONPATH:." #Needed to get tests to find main module
  - python -c "import sys;print(sys.path)"
  - pip install pytest
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml


package:
  stage: package
  artifacts:
    paths:
    - dist/*
  before_script:
  - pip install setuptools
  script:
  - python setup.py sdist
  needs: []


deploy:
  stage: deploy
  variables:
    REPO_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
  before_script:
  - pip install twine setuptools
  script:
  - python -m twine upload -u "gitlab-ci-token" -p ${CI_JOB_TOKEN} --repository-url $REPO_URL dist/*
  rules:
  - if: "$CI_COMMIT_TAG"
    when: always
  - when: never

docs:
  stage: docs
  before_script:
  - pip install sphinx sphinx-rtd-theme
  script:
  - sphinx-apidoc -M -o docs zip_deployer
  - sphinx-build -b html docs docs_build
  artifacts:
    paths:
      - docs_build
  needs: []