image: python:3.8

stages:
- deploy
- docs

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
  - .cache/pip
  - venv/

deploy:
  stage: deploy
  before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install twine setuptools
  script:
  - python setup.py sdist
  - twine upload --repository-url "http://192.168.1.100:14480" --username " " --password " " "dist/*"
  rules:
  - if: "$CI_COMMIT_TAG"
    when: always
  - when: never

docs:
  stage: docs
  before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install sphinx sphinx-rtd-theme
  script:
  - sphinx-apidoc -M -o docs zip_deployer
  - sphinx-build -b html docs docs_build
  rules:
  - if: "$CI_COMMIT_TAG"
    when: always
  - when: never
  artifacts:
    paths:
      - docs_build
    expire_in: 1 week